permalink: /:title/
repository: jimmgarrido/jimmgarrido.github.io
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge  

  #Jekyll-Photo-Gallery Settings
# exiftag:
#  sources:
#    - images/photography #Set to location of photos

#MiniMagick
#https://github.com/zroger/jekyll-minimagick
mini_magick:
    photography:
        source: images/photography
        destination: images/photography/thumbnails
        resize: "1280x720"
    headers:
        source: images/headers
        destination: images/headers/thumbnails
        resize: "400x250"